### PR TITLE
New features & refactoring

### PR DESCRIPTION
**Pull request by pigri**

### CODE REVIEW

**Comment by temp** [comment]
Tested your PR, since I didn't get the original running.
Your version works better, but I'm still having problems.

My setup: debian 7.5.0 with puppet 3.5.1, vagrant is 1.6.3, webserver module is apache2.
- I'm getting some deprecation warnings:

```
==> default: Warning: Variable access via 'root_password' is deprecated. Use '@root_password' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.pass.erb]:4
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.pass.erb:4:in `block in result')
==> default: Warning: Variable access via 'root_password' is deprecated. Use '@root_password' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.pass.erb]:5
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.pass.erb:5:in `block in result')
==> default: Warning: Variable access via 'port' is deprecated. Use '@port' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:2
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:2:in `block in result')
==> default: Warning: Variable access via 'socket' is deprecated. Use '@socket' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:3
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:3:in `block in result')
==> default: Warning: Variable access via 'socket' is deprecated. Use '@socket' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:5
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:5:in `block in result')
==> default: Warning: Variable access via 'pidfile' is deprecated. Use '@pidfile' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:9
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:9:in `block in result')
==> default: Warning: Variable access via 'socket' is deprecated. Use '@socket' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:10
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:10:in `block in result')
==> default: Warning: Variable access via 'port' is deprecated. Use '@port' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:11
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:11:in `block in result')
==> default: Warning: Variable access via 'basedir' is deprecated. Use '@basedir' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:12
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:12:in `block in result')
==> default: Warning: Variable access via 'datadir' is deprecated. Use '@datadir' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:13
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:13:in `block in result')
==> default: Warning: Variable access via 'bind_address' is deprecated. Use '@bind_address' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:17
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:17:in `block in result')
==> default: Warning: Variable access via 'bind_address' is deprecated. Use '@bind_address' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:18
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:18:in `block in result')
==> default: Warning: Variable access via 'log_error' is deprecated. Use '@log_error' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:28
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:28:in `block in result')
==> default: Warning: Variable access via 'default_engine' is deprecated. Use '@default_engine' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:31
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:31:in `block in result')
==> default: Warning: Variable access via 'ssl' is deprecated. Use '@ssl' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:34
==> default:    (at /tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb:34:in `block in result')
==> default: Warning: Variable access via 'altnames' is deprecated. Use '@altnames' instead. template[/tmp/vagrant-puppet-3/modules-0/openssl/templates/cert.cnf.erb]:14
==> default:    (at /tmp/vagrant-puppet-3/modules-0/openssl/templates/cert.cnf.erb:14:in `block in result')
==> default: Warning: Variable access via 'altnames' is deprecated. Use '@altnames' instead. template[/tmp/vagrant-puppet-3/modules-0/openssl/templates/cert.cnf.erb]:35
==> default:    (at /tmp/vagrant-puppet-3/modules-0/openssl/templates/cert.cnf.erb:35:in `block in result')
```
- Inside the vm, in /etc/ssl/private/appdev.cnf, a variable isn't replaced, I guess:

```
RANDFILE                = $ENV::HOME/.rnd
```

Which leads to several follow-up-errors
Anything I'm missing?
- Inside the vm, /etc/ssl/private/appdev.crt ist missing.

```
Error: Could not start Service[httpd]: Execution of '/etc/init.d/apache2 start' returned 1: Starting web server: apache2Syntax error on line 36 of /etc/apache2/sites-enabled/25-app.dev_ssl.conf:
SSLCertificateFile: file '/etc/ssl/private/appdev.crt' does not exist or is empty
Action 'start' failed.
The Apache error log may have more information.
 failed!
```

This might be follow-up-error.

**Comment by pigri** [comment]
I am so sorry. Only testing Ubuntu 12.04 / Ubuntu 14.04.

Next release fix Debian 7.5.x issues.

**Comment by temp** [comment]
No worries ;-)

Have you got an idea why $ENV::HOME is not replaced? Because of this everything else fails...

**Comment by pigri** [comment]
Yes understand... hmm... Please send me your box URL.

**Comment by temp** [comment]
Got it only on my dev machine here. It's a box built with packer, configuration is from https://github.com/ffuenf/vagrant-boxes.git

I'll try to put the box somewhere.

**Comment by pigri** [comment]
Thanks!

**Comment by temp** [comment]
You can fetch the box here: http://temporary.de/debian-7.5.0-amd64_virtualbox.box
Please tell me when you did, so I can remove it afterwards...

**Comment by pigri** [comment]
Finish.

**Comment by temp** [comment]
I tried it with an ubuntu 14.04 box, I'm getting the same error in /etc/ssl/private/appdev.cnf

```
RANDFILE                = $ENV::HOME/.rnd
```

$ENV::HOME should be replaced by a real path, correct?

**Comment by pigri** [comment]
Yes, that's correct. Please test this box sincerely/trusty64.

**Comment by temp** [comment]
Hmm, but I need to use a base box that is from a trusted source, company policy.
So we need to build our own boxes.

Too bad I only recently started using puppet, so I (yet) haven't got a clue what is going wrong here.

**Comment by temp** [comment]
Ok, my problem is described here: https://github.com/camptocamp/puppet-openssl/pull/31
I'll try the suggested solution there. Hopefully the PR will be merged soon, maybe you can update your PR afterwards.

**Comment by pigri** [comment]
Ok, I patching my code. https://github.com/pigri/default-vagrant

**Comment by temp** [comment]
Works fine now!
Any chance you can eliminate the deprecation warnings from my first post? They are all in the mysql-templates. Just add a @ before all variables.

**Comment by pigri** [comment]
Fixed :).

**Comment by temp** [comment]
Sorry, but you missed 4 lines ;-)

```
=> default: Warning: Variable access via 'root_password' is deprecated. Use '@root_password' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.pass.erb]:4
==> default: Warning: Variable access via 'bind_address' is deprecated. Use '@bind_address' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:17
==> default: Warning: Variable access via 'default_engine' is deprecated. Use '@default_engine' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:31
==> default: Warning: Variable access via 'ssl' is deprecated. Use '@ssl' instead. template[/tmp/vagrant-puppet-3/modules-0/mysql/templates/my.cnf.erb]:34
```

;-)

**Comment by pigri** [comment]
Fixed :)

**Comment by pigri** [comment]
@temp works?:)

**Comment by temp** [comment]
Works fine, thanks!

**Comment by pigri** [comment]
Postgresql & SMTP, Centos support! :)

**Pull request closed without merging**
